# yml from https://github.com/Tony0812-dev/AndroidLibV2rayLite

name: build

permissions:
  contents: write
  
on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        
      - name: Setup Go Mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:~/go/bin
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
        
      - name: Build Lib
        run: |
          gomobile init
          go mod tidy -v
          gomobile bind -v -androidapi 19 -ldflags='-s -w' ./
          
          
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lib
          path: |
            libv2ray.aar
            libv2ray-sources.jar
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          release_name: rel
          files: libv2ray*r
          prerelease: false
          generate_release_notes: true